# permissions for end users to view memorylimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memorylimit-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: policy-controller
    app.kubernetes.io/part-of: policy-controller
    app.kubernetes.io/managed-by: kustomize
  name: memorylimit-viewer-role
rules:
- apiGroups:
  - policy.sealos.io
  resources:
  - memorylimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.sealos.io
  resources:
  - memorylimits/status
  verbs:
  - get
