---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.sealos.io
  resources:
  - memorylimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.sealos.io
  resources:
  - memorylimits/finalizers
  verbs:
  - update
- apiGroups:
  - policy.sealos.io
  resources:
  - memorylimits/status
  verbs:
  - get
  - patch
  - update
